//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageHandling.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class PRODUCT
    {
        public int PRODID { get; set; }
        public string PRONAME { get; set; }
        public Nullable<int> CATID { get; set; }
        public Nullable<int> SUBID { get; set; }
        public Nullable<int> BRANDID { get; set; }
        public Nullable<double> PROPRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string PIMG { get; set; }
        public string DESCR { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public HttpPostedFileBase ImgPath { get; set; }
        public virtual BRAND BRAND { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
    }
}
