//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1603E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        public int ID { get; set; }
        public string MOBILENAME { get; set; }
        public string BRAND { get; set; }
        public string DETAILS { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string IMG { get; set; }
        public string MODEL { get; set; }
        public string CAMERA { get; set; }
    }
}
