//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PROID { get; set; }
        public string PRO_NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> CATID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
