//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROGRAM
    {
        public int ID { get; set; }
        public string PROG_NAME { get; set; }
        public int SEM_CURRCULUM { get; set; }
    }
}
