//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_REGISTRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATCH_REGISTRATION()
        {
            this.FACUTLY_BATCH = new HashSet<FACUTLY_BATCH>();
            this.SKILLS = new HashSet<SKILL>();
            this.STUDENTINFOes = new HashSet<STUDENTINFO>();
        }
    
        public int BACTCH_NO { get; set; }
        public string TIME_SLOT { get; set; }
        public Nullable<int> DAYID { get; set; }
        public int ENROLL_STD { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime EX_END_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public string REMARKS { get; set; }
        public int ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACUTLY_BATCH> FACUTLY_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKILL> SKILLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENTINFO> STUDENTINFOes { get; set; }
    }
}
