//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXREPORT
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string BATCHID { get; set; }
        public Nullable<int> SEM_ID { get; set; }
        public string SemesterName { get; set; }
        public Nullable<double> ExamCode { get; set; }
        public string ExamName { get; set; }
        public Nullable<double> MarksObtained { get; set; }
        public string ExamType { get; set; }
        public string ExamDate { get; set; }
    }
}
