//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACUTLY_BATCH
    {
        public int FA_BA_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string FA_CODE { get; set; }
        public Nullable<int> FA_BATCHNO { get; set; }
        public string FA_TIME_SLOT { get; set; }
    
        public virtual BATCH_REGISTRATION BATCH_REGISTRATION { get; set; }
        public virtual FACULTY FACULTY { get; set; }
    }
}
