//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTINFO
    {
        public int ID { get; set; }
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_FNAME { get; set; }
        public byte[] STD_PIC { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GENDER { get; set; }
        public string PROG_NAME { get; set; }
        public Nullable<int> BATCH_NO { get; set; }
        public string TIME_SLOT { get; set; }
        public string EMAIL_ID { get; set; }
        public string PAR_EMAIL_ID { get; set; }
        public string HOME_ADDRE { get; set; }
        public Nullable<int> SEM_ID { get; set; }
        public Nullable<int> ISSTC { get; set; }
    
        public virtual BATCH_REGISTRATION BATCH_REGISTRATION { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
    }
}
