//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMBATCHINFO
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public Nullable<int> BATCH_NO { get; set; }
        public string TIME_SLOT { get; set; }
        public string PROG_NAME { get; set; }
        public Nullable<int> SEM_ID { get; set; }
    }
}
