//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMBACTH_FA
    {
        public int ID { get; set; }
        public string FA_NAME { get; set; }
        public string FA_EMAILID { get; set; }
        public string BATCHDATA { get; set; }
        public int ENROLL_STD { get; set; }
        public string DAYS_CODE { get; set; }
    }
}
