//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSTDLOG
    {
        public int STD_ID { get; set; }
        public string STD_STATUS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string STD_MONTH { get; set; }
    }
}
