//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAptechMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSTDETAIL
    {
        public int STD_ID { get; set; }
        public string BATCHID { get; set; }
        public string STD_NAME { get; set; }
        public byte[] STD_PIC { get; set; }
        public Nullable<int> GENDER { get; set; }
        public string SEM_TITLE { get; set; }
        public string PROG_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<int> SEM_ID { get; set; }
        public Nullable<int> ISSTC { get; set; }
        public string PRIM_NUM { get; set; }
        public string SECON_NUM { get; set; }
        public string SMS_NUM { get; set; }
        public string OTHER_NUM { get; set; }
        public Nullable<int> NO_ATTENDED { get; set; }
        public int STATUS { get; set; }
    }
}
