//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<int> PRO_QT { get; set; }
        public Nullable<double> PRO_PRICE { get; set; }
        public Nullable<int> CAT_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
