//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvc02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string MODEL { get; set; }
        public string BRAND { get; set; }
        public string IMGPATH { get; set; }
    }
}
